# Generated by Django 2.2.1 on 2019-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
