# Generated by Django 2.2.1 on 2019-05-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0004_auto_20190509_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='write.Blog')),
            ],
        ),
    ]
