# Generated by Django 2.2.1 on 2019-05-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_image',
        ),
    ]
