# Generated by Django 2.2.1 on 2019-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0006_remove_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_image/'),
        ),
    ]
